name: COT weekly fetch

on:
  schedule:
    # 3:31 PM EDT (UTC-4) — roughly Mar–Nov
    - cron: "31 19 * * 5"
    # 3:31 PM EST (UTC-5) — roughly Nov–Mar
    - cron: "31 20 * * 5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        env:
          OUT_DIR: data
          YEARS_BACK: "0"
        run: python cot_fetch.py

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "COT update: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
